apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "naisd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "naisd.fullname" . }}
spec:
  rules:
  - host: "{{ .Values.ingress }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "naisd.fullname" . }}
          servicePort: 80
