apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "naisd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "naisd.fullname" . }}
type: Opaque
data:
  AZURE_AD_SERVICE_PRINCIPAL_APP_ID: {{ .Values.AzureAdServicePrincipalAppId | b64enc }}
  AZURE_AD_SERVICE_PRINCIPAL_PASSWORD: {{ .Values.AzureAdServicePrincipalPassword | b64enc }}
  AZURE_AD_SERVICE_PRINCIPAL_TENANT: {{ .Values.AzureAdServicePrincipalTenant | b64enc }}

